name: CI (Quick)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install CI deps (lightweight)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt

    - name: Run tests
      run: pytest -v tests/test_health_quick.py

    # Optional: build Docker image to prove it builds (skip push)
    - name: Build Docker image
      run: docker build -t myapp:ci .
